version: "3.9"
volumes:
  .venv:
services:
  app:
    build:
      context: api
      dockerfile: dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/api/credentials.json
    working_dir: /home/api/scan-pyproject
    command: /home/api/.rye/shims/rye run uvicorn api.app:app --port=8000 --host=0.0.0.0
    ports:
      - "8000:8000"