FROM ubuntu:22.04

RUN apt update
RUN apt install -y curl git
RUN useradd api --create-home

USER api
WORKDIR /home/api

RUN curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
RUN echo 'source "$HOME/.rye/env"' >> ~/.bashrc

COPY ./core/ /home/api/core
COPY ./app.py /home/api/app.py
COPY ./__init__.py /home/api/__init__.py
COPY ./.python-version /home/api/.python-version
COPY ./pyproject.toml /home/api/pyproject.toml
COPY ./credentials.json /home/api/credentials.json
COPY ./README.md /home/api/README.md

RUN bash -c "/home/api/.rye/shims/rye sync"

CMD [ "/bin/bash" ]