FROM ubuntu:22.04

RUN apt update
RUN apt install -y curl git
RUN useradd api --create-home

USER api
WORKDIR /home/api

RUN curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
RUN echo 'source "$HOME/.rye/env"' >> ~/.bashrc

RUN git clone https://github.com/yuta0306/scan-pyproject

CMD [ "/bin/bash" ]